"""empty message

Revision ID: 67468c79c8f6
Revises: d5fab6239fb0
Create Date: 2019-10-03 10:51:42.760907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67468c79c8f6'
down_revision = 'd5fab6239fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto')
    # ### end Alembic commands ###
