"""empty message

Revision ID: b0fb186c87af
Revises: 67468c79c8f6
Create Date: 2019-10-03 11:10:16.967905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fb186c87af'
down_revision = '67468c79c8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tarefa', 'projeto', ['projeto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.drop_column('tarefa', 'projeto_id')
    # ### end Alembic commands ###
